name: Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        container: 
            image: node:22
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with: 
                node-version: 22
            - run: npm ci
            - run: npm run test
            - run: npm run build
            
